### ISSUE TITLE
LICENSE file not given

### ISSUE THREAD

**Issue by dvtate** [team4226/kiosk#1]
If you're going to post software on GitHub, you should give it a `LICENSE` file. If you don't want people using your code, I would highly recommend against posting it publicly on GitHub as it was made to share <b>free software</b> (FOSS). 

I would recommend spending a day/meeting teaching your programming team members about software Licensing (I did this with my team before signing everyone up for GitHub). I would recommend using a GPL-compatible license, since your robotics team is [hopefully] a non-profit, and a license based on what you have written in your README doesn't really fit. You can also include a non-commercial clause if you wish.

I recommend reading this: https://www.chiefdelphi.com/forums/showthread.php?t=119469

Please note that you have no right to stop other users from forking your GitHub repositories, modifying them, and redistributing them. Although you have ownership over your own file, those who fork your file can do as they please (Unless they attempt use it to make a profit). 
![image](https://cloud.githubusercontent.com/assets/15305612/21576773/d047891a-cf0a-11e6-9b3d-374cbb8dd647.png)

If you want to use GitHub and want your projects' code to be protected from people who want to use it in their own projects, you can upgrade to a corporate account and make private repos, but I wouldn't waste your team's money.

Please feel free to contact me, I'm the programming team captain for FRC team # 4941 (RoboBibb). I like to collaborate with other teams on code and such. :smiley:

**Comment by team4226** [comment]
Thanks for the heads up. We are purely using this as a backup for our code, but we will be switching to a new backup system soon to prevent other teams from using our programs, as we are holding a creative commons to them.
